	<div class="outer_header">
        <header class="header">
            <img class="Left_panel" id="logo" src="images/logo.png" alt="Logo"> <!--https://www.brandcrowd.com/maker/logo/75a6c0be-eb8e-45f4-b771-768aae751480 --> 
            <h1 class="Left_panel"> THE OFF-ROAD BIKES </h1>
            <!-- Navigation --> 
            <div class="Right_panel">
                <nav class="Navigation">
                    <a class ="active" href="./index.php">Home</a> 
                    <a href="./product.php">Products</a>
                    <a href="./enquire.php">Purchase</a>
                    <a href="./manager.php">Manager</a>
                </nav>
                <form method="post" action="http://mercury.swin.edu.au/it000000/formtest.php">
                    <p class="search_bar">
                        <input placeholder="Search here..." type="text" name="search" id="search_bar" size="20"/>
                        <button class="search-icon"><img src="images/search-icon.png" alt="search-icon" height="14" width="20"></button> <!-- https://www.hiclipart.com/free-transparent-background-png-clipart-qyxpe-->
                    </p>
                </form>
                <form action="./product.php">
                <button class="add_cart">
			<a href='./enquire.php'>
			<img src="images/cart-icon.png" alt="cart-icon">
			</a>
		</button> <!-- https://sciconbags.com/media/cart-icon-header.png -->
                </form> 
            </div>
        </header>
	</div>
