<aside class="side_panel">
		<h3 id="side_heading"> <strong> Subscribe to our newsletter </strong> </h3>
		<p><img id="email-icon" src="images/email-icon.png" alt="email-icon"> Sign up for the latest news, updates and sales on our products</p> <!-- https://d1vexzcbxd5bk9.cloudfront.net/cdn/544265/media/wysiwyg/EMAIL-FOOTER_1.png -->
		<form method="post" action="http://mercury.swin.edu.au/it000000/formtest.php">
			<input placeholder="Enter E-mail here..." type="text" name="email" id="email" size="20"/>
			<p id = "email_btn"><button>Subscribe</button></p>
		</form>
		<hr>
		<h3> NEED HELP? REACH US AT: </h3>
		<ul class="Contact">
			<li><span class="glyphicon glyphicon-earphone" id="phone">Telephone-Support: 0416-111-111</span>
			</li>

			<li><span class="glyphicon glyphicon-envelope" id="envelope"><a href = "mailto:abc@gmail.com">support@offroad.com</a></span>
			</li>
		</ul>
		<h3 id="store_date_header"> Our Opening Hours: </h3>
			<table>
				<tr>
					<th>Day</th>
					<th>Opening</th>
					<th>Closing</th>
				</tr>
				<tr>
					<td>Monday</td>
					<td>9am</td>
					<td>5pm</td>
				</tr>
				<tr>
					<td>Tuesday</td>
					<td>9am</td>
					<td>5pm</td>
				</tr>
				<tr>
					<td>Wednesday</td>
					<td>9am</td>
					<td>5pm</td>
				</tr>
				<tr>
					<td>Thursday</td>
					<td>9am</td>
					<td>5pm</td>
				</tr>
				<tr>
					<td>Friday</td>
					<td>9am</td>
					<td>5pm</td>
				</tr>
				<tr>
					<td>Saturday</td>
					<td class="closed" colspan="2">Closed</td>
				</tr>
				<tr>
					<td>Sunday</td>
					<td class="closed" colspan="2">Closed</td>
				</tr>
			</table>
		</aside>